In [1]:
import numpy

ModuleNotFoundError: No module named 'numpy'

In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/12.6 MB 9.1 MB/s eta 0:00:02
   ----------- ---------------------------- 3.7/12.6 MB 9.1 MB/s eta 0:00:01
   ----------------- ---------------------- 5.5/12.6 MB 8.8 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.6 MB 8.9 MB/s eta 0:00:01
   ----------------------------- ---------- 9.4/12.6 MB 8.9 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.6 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 8.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((5,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [8]:
import time
print (time)

<module 'time' (built-in)>


In [9]:
z = np.full((3,5),3)
print(z)
s = z.T
print(s)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


In [ ]:
arr = [10,20,30,40]


In [ ]:
a = np.where(arr<20)
print(idx)

TypeError: '<' not supported between instances of 'list' and 'int'

: 